### ISSUE TITLE
5.5.2版本在 HarmonyOS NEXT 上打字时键盘会隐藏

### ISSUE THREAD

**Issue by ljje-lze** [byteburgers/react-native-autocomplete-input#328]
I press a number the cell phone keyboard is hidden

**Comment by mrlaessig** [comment]
This issue should be resolved in [releases/tag/v5.5.3](https://github.com/byteburgers/react-native-autocomplete-input/releases/tag/v5.5.3). Please feel free to reopen if the problem persists.
